services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-aggregator-app
    container_name: news-aggregator-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - news-aggregator-network
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: news-aggregator-nginx
    ports:
      - "9020:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - news-aggregator-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: news-aggregator-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: news-aggregator
      MYSQL_USER: news-aggregator
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - news-aggregator-network
    ports:
      - "3302:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: news-aggregator-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: news-aggregator
      PMA_PASSWORD: secret
    ports:
      - "9021:80"
    networks:
      - news-aggregator-network
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: news-aggregator-mailhog
    ports:
      - "1025:1025"  # smtp
      - "8025:8025"  # web ui
    networks:
      - news-aggregator-network

volumes:
  db_data:
  vendor_data:
  node_modules:

networks:
  news-aggregator-network:
    driver: bridge
